name: twttr
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  any_link_preview: ^3.0.0
  appwrite: ^9.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.5
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  image_picker: ^0.8.7+5
  json_annotation: ^4.8.1
  timeago: ^3.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
